version: '3.2'

services:
  syncthing:
    image: napnap75/rpi-syncthing
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - ./configs/syncthing:/var/syncthing/config
      - ../../NASSync:/var/syncthing/
  vpn:
    image: dperson/openvpn-client:armhf
    restart: unless-stopped
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    volumes:
      - ./configs/openvpn:/vpn
    dns:
      - '8.8.8.8'
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
        mode: host
      - target: 8112
        published: 8112
        protocol: tcp
        mode: host
  sonarr:
    image: dtroncy/rpi-sonarr
    privileged: true
    restart: unless-stopped
    volumes:
      - ../../NASMedia:/volumes/media
      - ../../NASDownloads/Torrents:/volumes/download
      - ./configs/sonarr:/volumes/config
    depends_on:
      - vpn
    network_mode: service:vpn
  deluge:
    image: jordancrawford/rpi-deluge
    privileged: true
    restart: unless-stopped
    volumes:
      - ./configs/deluge:/config
      - ../../NASDownloads/Torrents:/data
    depends_on:
      - vpn
    network_mode: service:vpn

