version: '3.2'

services:
  portainer:
    image: portainer/portainer:linux-arm
    container_name: 'portainer'
    ports:
      - '9000:9000'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    restart: always
  pihole:
    image: diginc/pi-hole-multiarch:debian_armhf
    container_name: 'pihole'
    ports:
      - '53:53/tcp'
      - '53:53/udp'
      - '80:80/tcp'
    environment:
      ServerIP: 192.168.1.13
      TZ: 'Australia/Melbourne'
    volumes:
      - '/media/usb/pihole.log:/var/log/pihole.log'
    restart: always
  syncthing:
    image: napnap75/rpi-syncthing
    container_name: 'syncthing'
    network_mode: host
    privileged: true
    restart: unless-stopped
    volumes:
      - ./configs/syncthing:/var/syncthing/config
      - ../../NASSync:/var/syncthing/
  vpn:
    image: dperson/openvpn-client:armhf
    container_name: 'vpn'
    restart: always
    cap_add:
      - net_admin
    security_opt:
      - label:disable
    volumes:
      - ./configs/openvpn:/vpn
    dns:
      - '8.8.8.8'
    ports:
      - target: 8989
        published: 8989
        protocol: tcp
        mode: host
      - target: 8112
        published: 8112
        protocol: tcp
        mode: host
  sonarr:
    image: dtroncy/rpi-sonarr
    container_name: 'sonarr'
    privileged: true
    restart: unless-stopped
    volumes:
      - ../../NASMedia:/volumes/media
      - ../../NASDownloads/Torrents:/volumes/download
      - ./configs/sonarr:/volumes/config
    depends_on:
      - vpn
    network_mode: service:vpn
  deluge:
    image: jordancrawford/rpi-deluge
    container_name: 'deluge'
    privileged: true
    restart: unless-stopped
    volumes:
      - ./configs/deluge:/config
      - ../../NASDownloads/Torrents:/data
    depends_on:
      - vpn
    network_mode: service:vpn

